Repository SRGSSR/castor, pull requests merged in 2025-05, with the labels that each got.

#82 Fix player layout on narrow devices
  Demo/Sources/Player/ControlsView.swift
Labels: bug

#83 Avoid potential name conflicts
  Demo/Sources/ExamplesView.swift
  Demo/Sources/Player/ControlsView.swift
  Package.swift
  Sources/Castor/Cast.swift
  Sources/Castor/CastAsset.swift
  Sources/Castor/CastConfiguration.swift
  Sources/Castor/CastExpandedMediaControlsView.swift
  Sources/Castor/CastMiniMediaControlsView.swift
  Sources/Castor/CastPlaybackConfiguration.swift
  Sources/Castor/CastPlayer.swift
  Sources/Castor/CastProgressTracker.swift
  Sources/Castor/CastSkip.swift
  Sources/Castor/Extensions/Slider.swift
  Sources/Castor/Extensions/View.swift
Labels: enhancement

#90 Add playback speed
  Demo/Sources/Player/ControlsView.swift
  Demo/Sources/Player/SettingsMenu.swift
  Sources/Castor/CastPlaybackSpeed.swift
  Sources/Castor/CastPlayer+SettingsMenu.swift
  Sources/Castor/CastPlayer.swift
  Sources/Castor/CastSeek.swift
  Sources/Castor/CastSettingsUpdate.swift
  Sources/Castor/Resources/Localizable.xcstrings
Labels: enhancement

#94 Support skips symbols based on player configuration
  Demo/Sources/DemoApp.swift
  Demo/Sources/Extensions/CastConfiguration.swift
  Demo/Sources/Extensions/Image.swift
  Demo/Sources/Extensions/UserDefaults.swift
  Demo/Sources/Player/ControlsView.swift
  Demo/Sources/SettingsView.swift
  Sources/Castor/Cast.swift
  Sources/Castor/CastPlayer.swift
Labels: enhancement

#97 Make amtins receiver support URNs
  Demo/Sources/ExamplesView.swift
  Demo/Sources/Player/PlaylistSelectionView.swift
  Demo/Sources/Receiver.swift
Labels: enhancement

#99 Reduce artwork image size
  Demo/Sources/Player/ControlsView.swift
  Gemfile.lock
  Scripts/public/build-demo.sh
  Scripts/public/test.sh
Labels: enhancement

#101 Support repeat modes
  Demo/Sources/Player/CastPlayerView.swift
  Demo/Sources/Player/PlaylistView.swift
  Sources/Castor/CastPlayer.swift
  Sources/Castor/CastRepeat.swift
  Sources/Castor/CastRepeatMode.swift
Labels: enhancement

#102 Fix nightly builds
  Scripts/private/deliver-demo.sh
Labels: bug

#108 Remove certificate import
  .github/workflows/nightlies.yml
  .github/workflows/releases.yml
  Scripts/private/add-apple-certificate.sh
  docs/CONTINUOUS_INTEGRATION.md
Labels: tooling
